### ISSUE TITLE
Aggregating Multiple Critical Paths from Many Traces

### ISSUE THREAD

**Issue by nsankar** [uber-research/CRISP#2]
@chabbimilind  I have a query on the subject matter mentioned [in the CRISP blog](https://eng.uber.com/crisp-critical-path-analysis-for-microservice-architectures/). At present, we are using CRISP with say the last 1 or 2 hour trace data pertaining to a specific Jaeger tracepath for which we specify the Service name and a Operation name to run CRISP analysis.

Can we load the data (say last 2hrs) from multiple trace paths as a source input -t in CRISP and then specify one or more service and operation names within the scope of the trace paths and run CRISP ?

Is there any other way to use CRISP in the context of  "Aggregating Multiple Critical Paths from **Many Traces**" ?

Thanks in advance.

**Comment by chabbimilind** [comment]
@nsankar currently we don't have this feature. It is possible to introduce such a feature, what are you expecting to see in the resulting report when there are multiple endpoints? Since the root of the call stacks will be different, the flamegraph will not combine the call stack, you will see two (or more) different roots. The heat maps can combine different roots since the rows are the endpoints, not call paths.

**Comment by nsankar** [comment]
@chabbimilind  Ok. This would be a useful feature to add on in CRISP. For example, tracepaths that has similar  business related flows/ functions in a group (for instance in payment related flows or database call flows) are potential candidates for an aggregated CP analysis in a distributed architecture.
